runtime: java17
#entrypoint: java -Dspring.profiles.active=dev -Xmx512m -jar becas-back-1.0.jar
#instance_class: F2
#env_variables:
#  PG_DB_USERNAME: 'DATA1'
#  PG_DB_PASSWORD: 'DATA2'
#automatic_scaling:
#  min_idle_instances: 1
#  max_idle_instances: 1
#
##manual_scaling:
##  instances: 1
#service: becas-back-dev
#handlers:
#  - url: /.*
#    script: this field is required, but ignored
